### PR TITLE
1: Install and configure VSCode

### LINKED ISSUE #1: Install and configure VS Code
Home page: https://code.visualstudio.com/

We can just install with Homebrew:

```bash
brew install visual-studio-code
```

Or we could use https://github.com/gantsign/ansible-role-visual-studio-code

### PR DESCRIPTION
**Pull request by benjifisher**
Resolves #1.

### CODE REVIEW

**Comment by benjifisher** [comment]
I think the third commit is not useful. I misunderstood the instructions in https://ddev.readthedocs.io/en/stable/users/debugging-profiling/step-debugging/#ide-setup:

> Update the project’s `.vscode/launch.json` to add the “Listen for Xdebug” configuration from [this config snippet](https://ddev.readthedocs.io/en/stable/users/snippets/launch.json). For more on customizing `launch.json`, see the [VS Code docs](https://code.visualstudio.com/docs/editor/debugging#_launch-configurations).

Or maybe I misunderstood the VS Code docs.

What works:

- Add `hwp-curie/.vscode/launch.json` using the recommended code snippet.
- Edit `~/Library/Application Support/Code/User/settings.json`, _inserting_ the recommended snippet.

What does not work: adding `~/.vscode/launch.json`.

To do: figure out the right place to put the file for global config, update the installation script to update `settings.json`, or add a file to the Drupal repo.

**Comment by benjifisher** [comment]
At some point, I used Homebrew to install PHP on the host. I forget: maybe I did not see how to install the Xdebug plugin, or activate it, without doing that. Or maybe I was having trouble starting an Xdebug session. I should test removing PHP from my Mac so that we can just use the version on the Docker containers.

In order to start an Xdebug session, a key step is to open the repository. For example, open from the VS Code application's File menu. Editing a file in the repo is not enough.

**Comment by benjifisher** [comment]
Replying to my own comments:

1. I rewrote history (`git rebase -i main`) and removed the not-useful commit.
2. I have not yet made a PR, but the `feature/trello-458-use-ddev` branch of https://github.com/harvard-web-publishing/hwp-curie/pulls includes `launch.json`. I also mention that in the wiki.
3. I removed PHP from my Mac and tested installing VS Code and Xdebug with this project. LGTM
4. On the wiki, I documented the steps to start a debugging session.
5. I added all the plugins from Carole's list, but commented them out for now. I tested installing them all (un-commenting them) and only one failed. I marked that one with a `FIXME` comment.

**Review by cemah-h — APPROVED** [review]
@benjifisher - one of the steps on the wiki home page says "Click on the green triangle next to "Listen for Xdebug" but I didn't see any such green triangle. It turns out that a debugging step is that if you do not see that triangle, it means you accidentally put the new `launch.json` file in the project root instead of where it belongs, in `.vscode/` -- somehow I didn't see that step at all, as it's not part of the actual list of steps. Other than that, I finally got it to work. Great job.

**Comment by benjifisher** [comment]
@cemah-h:

You got it to work: great!

I added a troubleshooting section to the wiki page. That particular problem should not come up once https://github.com/harvard-web-publishing/hwp-curie/pull/662 is merged, but eventually there will be other repositories that also need the "magic file".

**Pull request merged**
